# Site settings
title: welcome to my space
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  一个前端
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https//guoguangkun.github.io" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'


# Social account
# twitter:  username
# weibo:    ID
# github:   username
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
