# Site settings
title: welcome to my space
email: guoguangkun1024@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A front end developer,即使眼前的是狂风暴雨，但是远处的海平面依旧是风平浪静。
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "https://guoguangkun.github.io" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'


# Social account
# twitter:  username
# weibo:    ID
 github:   guoguangkun
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
